api/urls.py
from django.urls import path, include
from .views import GatewayProxyApi
# from rest_framework.routers import DefaultRouter

# from .views import CategoryViewSet, userCapabilities #CategoryListCreateApiView #categoryList

# router = DefaultRouter()
# router.register("categories", CategoryViewSet)

# urlpatterns = [
#     # path('categories/', categoryList)
#     path('categories/', CategoryListCreateApiView.as_view())
# ]
# urlpatterns = router.urls

# urlpatterns += [
#     path('capabilities/', userCapabilities, name='userCapabilities')
# ]

from .views import *

# app_name='gateway-proxy'
urlpatterns = [
    path('api/gateway/<str:service>/<path:path>', GatewayProxyApi.as_view(), name='gateway-proxy'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logoutGateway'),
    path('signup/',signUp, name='signup' ),
    path('createCategory/', createCategory, name='createCategory'),
    path('deleteCategory/<int:category_id>/', deleteCategory, name='deleteCategory'),
    path('products/', productList, name='products'),
    path('productsCreate/', createProductView, name='productsCreate'),
    path('productsCreateSubmit/', createProduct, name='productsCreateSubmit'),
    path('productsDelete/<int:product_id>/', deleteProduct, name='productsDelete'),
    path('productsUpdate/<int:product_id>/', updateProduct, name='productsUpdate'),
    path('categories/', categoryList, name='categories'),
    path('cart/', viewCart, name='viewCart'),
    path('cartAdd/<int:product_id>/', addToCart, name='cartAdd' )
]

base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('category/', include('category.urls')),
    path('', include('api.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
]

cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('list/', viewCart, name='viewCart'),
    path('add/<int:product_id>/', addToCart, name='addToCart' )
]

products/urls.py
from django.urls import path
from .views import *

app_name ='products'

urlpatterns = [
    path('list/', productList, name='products'),
    path('create/', createProduct, name='createProduct'),
    path('get/<int:product_id>/', getProduct, name='getProduct'),
    path('delete/<int:product_id>/', deleteProduct, name='deleteProduct'),
    path('update/<int:product_id>/', updateProduct, name="updateProduct")
]

cart/models.py
from django.db import models
from users.models import Users
from products.models import Products

# Create your models here.
class Cart(models.Model):
    # user = models.OneToOneField(Users, on_delete=models.CASCADE)
    user = models.PositiveIntegerField(unique=True) 
    

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        unique_together = ('cart', 'product')

cart/views.py
from django.shortcuts import render, redirect
from .services import CartService
from products.models import Products
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse
from .models import Cart, CartItem
from .serializers import CartItemSeralizer


# Create your views here.
@csrf_exempt
def viewCart(request):
    user = request.headers.get('X-User-Id')
    cart = Cart.objects.prefetch_related('items__product').get(user=user)
    items = cart.items.all()
    total = 0
    for item in items:
        total += item.product.price * item.quantity
    serializers = CartItemSeralizer(items, many=True)
    data = {
        'cart': cart.id,
        'items': serializers.data,
        'total': total
    }
    return JsonResponse({'data': data}, status=200)
    

@csrf_exempt
def addToCart(request, product_id):
    if request.method == 'POST':
        product = Products.objects.get(pk=product_id)
        user = request.headers.get('X-User-Id')
        cart = Cart.objects.get_or_create(user=int(user))[0]
        data = json.loads(request.body)
        item, created = CartItem.objects.get_or_create(
            cart=cart,
            product=product,
            defaults={'quantity': int(data.get('quantity', 1))}
        )
        if not created:
            item.quantity += int(data.get('quantity', 1))
        item.save()
        return JsonResponse({'message': 'Item added to cart successfully'}, status=200)

category/views.py
from django.shortcuts import render, redirect
from .models import Category
# from django.contrib.auth.decorators import login_required
# from rest_framework.test import APIClient
from .services import CategoryService
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json

# Create your views here.

app_name = 'category'


def categoryList(request):
    categories = Category.objects.all()
    return JsonResponse({'items': list(categories.values())})
    # categories = CategoryService.categoryList(request.user)
    # isProducer = CategoryService.canCreateAndModify(request.user)
    # return render(request, 'category/list.html', {'categories': categories, 'allowed': isProducer})

@csrf_exempt
def createCategory(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        Category.objects.create(name=data.get('name'))
        return JsonResponse({'status': 'success'}, status=200)

@csrf_exempt
def deleteCategory(request, category_id):
    if request.method == 'POST':
        category = Category.objects.get(pk=category_id)
        category.delete()
        return JsonResponse({'status': 'success'}, status=200)

theme/templates/cart/view.html
{% extends 'base.html' %}

{% block title %}
Cart
{% endblock %}

{% block content %}

    <table class="table-auto min-w-full border-separate">
        <thead>
            <tr >
                <th class='px-4 py-2 text-left text-md font-medium text-gray-800'>Product</th>
                <th class='px-4 py-2 text-left text-md font-medium text-gray-800'>Price</th>
                <th class='px-4 py-2 text-left text-md font-medium text-gray-800'>Quantity</th>
                <th class='px-4 py-2 text-left text-md font-medium text-gray-800'>SubTotal</th>
                {% comment %} {% if request.user.is_authenticated and request.user.role == 'Consumer' %} {% endcomment %}
                {% comment %} {% if allowed %}
                <th></th>
                <th></th>
                {% endif %}
                <th></th> {% endcomment %}
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-100">
            {% for item in items %}
            <tr class='odd:bg-blue-50 even:bg-white hover:bg-gray-50'>
                <td class="px-4 py-2">{{item.product}}</td>
                <td class="px-4 py-2 whitespace-nowrap">{{item.productPrice}}</td>
                <td class="px-4 py-2 whitespace-nowrap">{{item.quantity}}</td>
                <td class="px-4 py-2">{{item.subtotal}}</td>
                {% comment %} {% if request.user.is_authenticated and request.user.role == 'Consumer' %} {% endcomment %}
                {% comment %} {% if p.can_buy %}
                <td>
                    <a href="{% url 'cart:addToCart' p.id %}"
                    class="rounded-lg bg-green-600 px-4 py-2 text-sm font-small text-white hover:bg-green-700" 
                    >Buy</a>
                </td> {% endcomment %}
                {% comment %} {% endif %}
                {% if allowed %}
                {% if p.can_edit %}
                <td>
                    <a href="{% url 'products:updateProduct' p.id %}"
                    class="rounded-lg bg-gray-600 px-4 py-2 text-sm font-small text-white hover:bg-gray-700" 
                    >Update</a>
                </td>
                {% endif %}
                <td>
                    <form method="POST" action="{% url 'products:deleteProduct' p.id %}">
                        {% csrf_token %}
                        <button class="flex items-center justify-center p-2 text-red-600 rounded-full hover:bg-red-100 hover:text-red-800" type="submit" {% if not p.can_delete %}disabled{% endif %}>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.34 6.75m0 0a2.25 2.25 0 0 1 2.244-2.077h4.5a2.25 2.25 0 0 1 2.244 2.077M19.5 4.5h-15" />
                            </svg>
                        </button>
                    </form>
                </td>
                {% endif %} {% endcomment %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% comment %} <h3 class="decoration-emerald-100">Total Amount: {{ total }}</h3> {% endcomment %}


<h3 class="text-lg font-semibold text-black-900">
  Total Amount:
  <span class="text-emerald-600 dark:text-emerald-400 font-bold">
    {{ total }}
  </span>
</h3>

{% comment %} {% if allowed %}
<div class = "mt-8">
    <a href="{% url 'products:createProduct' %}" class="rounded-lg bg-gray-600 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700">Create New Product</a>
</div>
{% endif %} {% endcomment %}
{% comment %} 
{% if request.user.is_authenticated and request.user.role == 'Consumer' %}
<div class = "mt-8">
    <form method='POST' action="{% url 'category:createCategory' %}">
        {% csrf_token %}
        <label for="name">Category Name:</label>
        <input type="text" id="name" name="name" class="border border-gray-300 rounded-md p-1" />
        <button type="submit" class="ml-2 bg-indigo-600 text-white px-4 py-2 rounded-md hover:bg-indigo-700">Create</button>
    </form>
</div>
{% endif %} {% endcomment %}
{% endblock %}